name: kostamobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0-429.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  http: ^0.13.5
  fluttertoast: ^8.1.1

dev_dependencies: 
  pedantic:
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: IBM
      fonts:
        - asset: assets/fonts/IBM_Plex_Sans_KR/IBMPlexSansKR-Bold.ttf
          weight: 600
        - asset: assets/fonts/IBM_Plex_Sans_KR/IBMPlexSansKR-Regular.ttf
          weight: 300

    - family: SM
      fonts:
        - asset: assets/fonts/Song_Myung/SongMyung-Regular.ttf


